import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      "cdn-icons-png.flaticon.com",
      "i.pinimg.com",
      "images.unsplash.com",
      "example.com",
      "file.hstatic.net",
      "sushiworld.com.vn",
      "cdn.tgdd.vn",
      "www.shogun.nl",
      "www.justonecookbook.com",
      "www.sushitei.com",
      "www.thespruceeats.com",
      "www.example.com",
      "example.org",
      "example.net",
      "example.edu",
      "example.co.uk",
      "kenh14cdn.com",
      "example.io",
      "example.us",
      "example.ca",
      "ussinavietnam.vn",
      "satovietnhat.com.vn",
      "saigonreview.vn",
      "plus.unsplash.com",
      "wallpapers.com",
      "media.istockphoto.com",
      "t3.ftcdn.net",
      "phongcachmoc.vn",
      "cdn.pastaxi-manager.onepas.vn",
      "xuongmocso1.com",
      "fnb.qdc.vn",
      "pastaxi-manager.onepas.vn",
      "image.phunuonline.com.vn",
      "media.suckhoecong.vn",
      "xkld.thanhgiang.com.vn",
      "i0.wp.com",
      "kokugyu.com.vn",
      "product.hstatic.net",
      "vn.fishroe.net",
      "bizweb.dktcdn.net",
      "tournhatban.net",
      "bioplanet.vn",
      "danviet.ex-cdn.com",
      "res.klook.com",
      "thedotmagazine.com",
      "www.elledecoration.vn",
      "static.vecteezy.com",
      "127.0.0.1"
    ],
  },
};

module.exports = nextConfig;
